<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="2016\Day 12 - Leonardo's Monorail - Copy\input.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdventOfCode.Core\AdventOfCode.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="2015\" />
    <Folder Include="2016\" />
    <Folder Include="2017\" />
    <Folder Include="2018\" />
    <Folder Include="2019\" />
    <Folder Include="2020\" />
    <Folder Include="2021\" />
    <Folder Include="2022\" />
    <Folder Include="2023\" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<WarningsAsErrors />
	<CodeAnalysisRuleSet>..\AdventOfCode.ruleset</CodeAnalysisRuleSet>
	<NoWarn>1701;1702;S3247;</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<WarningsAsErrors />
	<CodeAnalysisRuleSet>..\AdventOfCode.ruleset</CodeAnalysisRuleSet>
	<NoWarn>1701;1702;S3247;</NoWarn>
  </PropertyGroup>
</Project>
