<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="34.0.2" />
    <PackageReference Include="FluentAssertions" Version="6.11.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.3" />
    <PackageReference Include="Moq" Version="4.18.4" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdventOfCode.Core\AdventOfCode.Core.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2015\AdventOfCode.Puzzles.2015.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2016\AdventOfCode.Puzzles.2016.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2017\AdventOfCode.Puzzles.2017.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2018\AdventOfCode.Puzzles.2018.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2019\AdventOfCode.Puzzles.2019.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2020\AdventOfCode.Puzzles.2020.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2021\AdventOfCode.Puzzles.2021.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2022\AdventOfCode.Puzzles.2022.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2023\AdventOfCode.Puzzles.2023.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2024\AdventOfCode.Puzzles.2024.csproj" />
	<ProjectReference Include="..\AdventOfCode.Puzzles.2025\AdventOfCode.Puzzles.2025.csproj" />
  </ItemGroup>

</Project>
