<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWindowsForms>true</UseWindowsForms>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ffmpeg.exe" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Runtime" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdventOfCode.Animation\AdventOfCode.Animation.csproj" />
    <ProjectReference Include="..\AdventOfCode.Core\AdventOfCode.Core.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2015\AdventOfCode.Puzzles.2015.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2016\AdventOfCode.Puzzles.2016.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2017\AdventOfCode.Puzzles.2017.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2018\AdventOfCode.Puzzles.2018.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2019\AdventOfCode.Puzzles.2019.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2020\AdventOfCode.Puzzles.2020.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2021\AdventOfCode.Puzzles.2021.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2022\AdventOfCode.Puzzles.2022.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2023\AdventOfCode.Puzzles.2023.csproj" />
    <ProjectReference Include="..\AdventOfCode.Puzzles.2024\AdventOfCode.Puzzles.2024.csproj" />
	<ProjectReference Include="..\AdventOfCode.Puzzles.2025\AdventOfCode.Puzzles.2025.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<WarningsAsErrors />
	<CodeAnalysisRuleSet>..\adventofcode.ruleset</CodeAnalysisRuleSet>
	<NoWarn>1701;1702;S3247;</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <CodeAnalysisRuleSet>..\adventofcode.ruleset</CodeAnalysisRuleSet>
    <NoWarn>1701;1702;S3247;</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<WarningsAsErrors />
	<CodeAnalysisRuleSet>..\adventofcode.ruleset</CodeAnalysisRuleSet>
	<NoWarn>1701;1702;S3247;</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <CodeAnalysisRuleSet>..\adventofcode.ruleset</CodeAnalysisRuleSet>
    <NoWarn>1701;1702;S3247;</NoWarn>
  </PropertyGroup>
</Project>
